server:
  port: 8080
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

# mybatis、logging 是公共配置，放这里没问题
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    com.sky.mapper: debug
    com.sky.service: info
    com.sky.controller: info

# JWT 属于通用的业务配置，可以放主配置, 管理端员工生成jwt令牌相关配置
sky:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication